"""add video_provider_upload_id to episodes

Revision ID: 625ecb3013f6
Revises: a1b2c3d4e5f6
Create Date: 2026-03-01 08:51:15.397594

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '625ecb3013f6'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'episodes',
        sa.Column('video_provider_upload_id', sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'video_provider_upload_id')
    # ### end Alembic commands ###
